import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'
import messages from '../../../messages/en.json'
import { unstable_setRequestLocale } from 'next-intl/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'lv', 'ru']

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  if (!locales.includes(locale as any)) {
    notFound()
  }
  unstable_setRequestLocale(locale)

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
        <body className={inter.className}>{children}</body>
      </html>
    </NextIntlClientProvider>
  )
}
